name: flutterquiz
description: A new Flutter application.
publish_to: "none"
version: 2.2.0+44

# Release Version: 2.2.1 (do not remove or edit this)
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.3.0
  connectivity_plus: ^6.0.5
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  encrypt: ^5.0.3
  firebase_analytics: ^11.3.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_tex: ^4.0.9
  flutter_widget_from_html: ^0.15.2
  flutter_windowmanager: ^0.2.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  http: ^1.2.2
  iabtcf_consent_info: ^3.1.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  internet_connection_checker: ^2.0.0
  intl: ^0.19.0
  ios_insecure_screen_detector: ^0.0.2
  just_audio: ^0.9.40
  lottie: ^3.1.2
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  scratcher: ^2.5.0
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.2
  unity_ads_plugin: ^0.3.20
  url_launcher: ^6.3.0
  wakelock_plus: ^1.2.8


dev_dependencies:
  change_app_package_name: ^1.3.0
  dart_code_metrics_presets: ^2.14.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile/

    - assets/images/emojis/

    - assets/languages/
    - assets/animations/

    - assets/sounds/
    - assets/files/
